name: Run UFT One Tests Action
# Controls when the action will run. Workflow runs when manually triggered using the UI or API.

on:
  workflow_dispatch:

env:
  PROPS_TXT: PropsMultiTests.txt
  RES_XML: ResultsMultiTests.xml
  LAUNCHER_EXE: FTToolsLauncher.exe
  LAUNCHER_URL: https://github.com/MicroFocus/ADM-FT-ToolsLauncher/releases/download/v25.2.0/FTToolsLauncher_net48.exe
  REPORT_EXE: ReportConverter.exe
  OUT_REPORT: C:\Users\mortiz2\Desktop\Git Repository\GitActions\MyRepository\27032026_junit_report.xml
  RESULTS_PATH: C:\Users\mortiz2\Desktop\Git Repository\GitActions\MyRepository\MyFirstScript\Report1

defaults:
  run:
    shell: pwsh
    working-directory: ..\

jobs:
  getUftTests:
    runs-on: self-hosted
    steps:
    - name: Display the working directory
      run: echo "$pwd"

  createPropsFile:
    runs-on: self-hosted
    needs: getUftTests
    steps:
    - name: Create properties file
      run: |
        @"
        runType=FileSystem
        Test1=C:\\Users\\mortiz2\\Desktop\\Git Repository\\GitActions\\MyRepository\\MyFirstScript
        resultUnifiedTestClassname=true
        resultTestNameOnly=true
        resultsFilename=$env:RES_XML
        "@ > $env:PROPS_TXT
    - name: Check properies file
      run: TEST-PATH $env:PROPS_TXT

  getFTToolsLauncher:
    runs-on: self-hosted
    needs: getUftTests
    steps:
    - name: GET FTToolsLauncher.exe
      run:  if (TEST-PATH $env:LAUNCHER_EXE) {
              echo "FTToolsLauncher.exe already exists"
            } else {
              curl -L -o $env:LAUNCHER_EXE $env:LAUNCHER_URL
            }

  runUftTestsFromFileSystem:
    runs-on: self-hosted
    needs: [getUftTests, createPropsFile, getFTToolsLauncher]
    steps:
    - name: Run FT tool
      id: run-tests
      run: |
        $p = Start-Process -FilePath "$env:LAUNCHER_EXE" -ArgumentList "-paramfile $env:PROPS_TXT" -Wait -PassThru -NoNewWindow
        "X=$($p.ExitCode)" >> $env:GITHUB_OUTPUT
    - if: ${{steps.run-tests.outputs.X != 0}}
      uses: actions/github-script@v6
      with:
        script: |
          core.setFailed('The job runUftTestsFromFileSystem failed with status ${{steps.run-tests.outputs.X}} !')       

          
  runReportConverter:
    runs-on: self-hosted
    needs:  runUftTestsFromFileSystem
    steps:
    - name: Run ReportConverter
      id: convert-results 
      run: |
        $p = Start-Process -FilePath "$env:REPORT_EXE" -ArgumentList "-j  C:\Users\mortiz2\Desktop\Git Repository\GitActions\MyRepository\27032026_junit_report.xml C:\Users\mortiz2\Desktop\Git Repository\GitActions\MyRepository\MyFirstScript\Report1"
        "X=$($p.ExitCode)" >> $env:GITHUB_OUTPUT
